export const EMPTY_ERR = "EMPTY_ERR";
export const PASSWORD_ERR = "PASSWORD_ERR";
export const CLEAR_TEXT = "CLEAR_TEXT";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS ";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const VERIFIED_SUCCESS = "VERIFIED_SUCCESS ";
export const VERIFIED_ERROR = "VERIFIED_ERROR";
export const PASSWORD_RECOVERY_ERROR = "PASSWORD_RECOVERY_ERROR";
export const USER_EMAIL_FOUND = "USER_EMAIL_FOUND";
export const CHECKTOKEN_ERROR = "CHECKTOKEN_ERROR";

export const INVALID_TOKEN = "INVALID_TOKEN";
export const PASSWORD_MISMATCH = "PASSWORD_MISMATCH";
export const PASSWORD_CHANGED_SUCCESS = "PASSWORD_CHANGED_SUCCESS";

export const UPLOAD_MUSIC_ERROR = "UPLOAD_MUSIC_ERROR";
export const UPLOAD_MUSIC_SUCCESS = "UPLOAD_MUSIC_SUCCESS";
export const UPLOAD_VALIDATION = "UPLOAD_VALIDATION";
export const GETMYSONG_ERROR = "GETMYSONG_ERROR";
export const SET_MY_SONGS = "SET_MY_SONGS";

export const SET_SINGLE_SONG = "SET_SINGLE_SONG";
export const SET_SINGLE_SONG_ERROR = "SET_SINGLE_SONG_ERROR";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_ALL_SONGS = "GET_ALL_SONGS";

export const SEARCH_ERROR = "SEARCH_ERROR";
export const GET_SEARCHED_SONG = "GET_SEARCHED_SONG";

export const SONG_DELETED = "SONG_DELETED";

export const SONG_EDIT_SUCCESS = "SONG_EDIT_SUCCESS";
export const INVALID_USER_ERR = "INVALID_USER_ERR";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";

export const SET_RELOADED = "SET_RELOADED"

export const LOAD_PAGE = "LOAD_PAGE"
export const GET_ALL_VERIFIED_SONGS = "GET_ALL_VERIFIED_SONGS"
export const SONG_APPROVED = "SONG_APPROVED"
export const GET_ADMIN_DASHBOARD_INFO = "GET_ADMIN_DASHBOARD_INFO"
export const GET_TRENDING_SONGS = "GET_TRENDING_SONGS"
export const GET_RANDOM_SONGS = "GET_RANDOM_SONGS"
export const SET_LOADER = "SET_LOADER"
export const UNSET_USERNAME = "UNSET_USERNAME"
export const IS_USER_LOGGED_IN = "IS_USER_LOGGED_IN"
export const  IS_USER_LOGGED_OUT= " IS_USER_LOGGED_OUT"
export const  SET_INITIALSTATE= " SET_INITIALSTATE"
export const  TOKEN_IS_SET= " TOKEN_IS_SET"
export const  TOKEN_IS_NOT_SET= " TOKEN_IS_NOT_SET"
export const  SET_PRODUCT_TYPE= " SET_PRODUCT_TYPE"





